### ISSUE TITLE
IOS pod issue

### ISSUE THREAD

**Issue by ashish2583** [network-international/react-native-ngenius#12]
I am getting issue when going to pod install in ios 
issue atteched in screensh
<img width="573" alt="Screenshot 2021-11-06 at 7 48 58 PM" src="https://user-images.githubusercontent.com/47518056/140691562-404996ac-4d65-482a-be94-776338f74507.png">

**Comment by suzTheCoder** [comment]
create an empty File.swift in your root project>projectName

**Comment by suzTheCoder** [comment]
Change ios deployment target to 11.0 in xcode and in podfile.
Also, I added an empty File.swift file at the same level of podfile to make this work.
