### ISSUE TITLE
Samsung Pay : int com.facebook.react.bridge.ReadableArray.size()

### ISSUE THREAD

**Issue by thanveershah** [network-international/react-native-ngenius#14]
I get the following error when trying to Initiate Samsung Pay.

These are my project versions
"react": "17.0.1"
"react-native": "^0.63.4"
"@network-international/react-native-ngenius": "^1.0.9"

ext:
buildToolsVersion = "29.0.3"
minSdkVersion = 21
compileSdkVersion = 30
targetSdkVersion = 30
ndkVersion = "20.1.5948944"
supportLibVersion = "28.0.0"

![processed-23e22979-3796-4d35-80d1-f454c1625253_C9hNTXbc](https://user-images.githubusercontent.com/44460964/144749282-7f368ed2-2e59-4eae-81ba-77bd1d24ac7e.jpeg)

**Comment by mu1ex** [comment]
Please use `isSamsungPaySupported("serviceId")` before initiating Samsung Pay
