### ISSUE TITLE
> compileSdkVersion is not specified. Please add it to build.gradle

### ISSUE THREAD

**Issue by Diyaa-Gubarah** [network-international/react-native-ngenius#18]
when I try to start `npm run android` the following error occurs.

# What went wrong:
> A problem occurred evaluating project ':network-international_react-native-ngenius'.
> Plugin with id 'maven' not found.

> A problem occurred configuring project ':network-international_react-native-ngenius'.
> compileSdkVersion is not specified. Please add it to build.gradle.

my package.json
`
"@network-international/react-native-ngenius": "^1.1.4",
"react": "17.0.2",
"react-native": "0.68.2"`

my app/build.gradle 
`
buildToolsVersion = "31.0.0"
minSdkVersion = 21
compileSdkVersion = 31
targetSdkVersion = 31
`

**Comment by HadiKhalifeh** [comment]
@Diyaa-Gubarah did you found the issue

**Comment by Diyaa-Gubarah** [comment]
No, I didn't

But I downgrade the react native from 0.70 to 0.66 it seems your library
not working with gradle
version start from 0.7.+.

Please don't update your library I faced difficult time try to fix this
problem 😂🤣. Now it's work fine.

**Comment by HadiKhalifeh** [comment]
@Diyaa-Gubarah please can you share with me tools build.gradle and gradle version, which version you are using now i'm facing new issue using this library

`Execution failed for task ':app:javaPreCompileDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Failed to transform bcprov-jdk15on-1.65.jar (org.bouncycastle:bcprov-jdk15on:1.65) to match attributes {artifactType=android-classes, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.`

**Comment by Diyaa-Gubarah** [comment]
Sure.



Just use react native version 0.66 rather than last version.

You don't need to do anything else.


Npx react-native init yourappname --version 0.66.0

And then install the library.

**Comment by mu1ex** [comment]
We have updated the SDK to support latest versions of react. Can you check again with the latest version and reopen if issue still persists
