### ISSUE TITLE
#error unsupported Swift architecture

### ISSUE THREAD

**Issue by kareem-ali-abdelsalam** [network-international/react-native-ngenius#21]
Hello, 

After running pod install with version 1.1.4 (current version) or 1.1.6 (last update), 
we noticed "Installing NI-Three-DS-Two-iOS-SDK (1.0.0)" 
NI-Three-DS-Two-iOS-SDK installed and after that we got this error 
"#error unsupported Swift architecture" and build couldn't be complete 

RN v0.70.1
React v18.1.0

What is the issue ?

**Comment by kareem-ali-abdelsalam** [comment]
@mu1ex Kindly reminder !

**Comment by mu1ex** [comment]
@kareem-ali-abdelsalam , the sdk is not compatible with simulator. Please run it on a real device

**Comment by kareem-ali-abdelsalam** [comment]
@mu1ex Also Is it working on latest version 0.70.2 ?

**Comment by mu1ex** [comment]
What Swift version is your app on?

**Comment by kareem-ali-abdelsalam** [comment]
@mu1ex  issue fixed but we can't use the simulator, do you have any workaround ?

**Comment by mu1ex** [comment]
This issue is fixed in the latest simulator version

**Comment by OmarUsman777** [comment]
@mu1ex just a gentle question, we are planning to implement [react-native-ngenius] SDK in our new project, we're using React Native 0.78.2 (New Architecture) for our new project. Will the react-native-ngenius SDK work fine with this RN version?
