### ISSUE TITLE
Build Failed When npm run ios on simulator.

### ISSUE THREAD

**Issue by Diyaa-Gubarah** [network-international/react-native-ngenius#22]
this error occurs when i try to run `npm run ios` , I don't have Apple Developer Account how to test in `simulator`.

```

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_UChallengeParameters", referenced from:
      objc-class-ref in NISdk(ThreeDSTwoViewController.o)
  "_OBJC_CLASS_$_UConfigParameters", referenced from:
      objc-class-ref in NISdk(NISdk.o)
  "_OBJC_CLASS_$_UUiCustomization", referenced from:
      objc-class-ref in NISdk(NISdk.o)
  "_OBJC_CLASS_$_UDirectoryServer", referenced from:
      objc-class-ref in NISdk(NISdk.o)
  "_OBJC_CLASS_$_UThreeDS2ServiceImpl", referenced from:
      objc-class-ref in NISdk(PaymentViewController.o)
      objc-class-ref in NISdk(NISdk.o)
      objc-class-ref in NISdk(ThreeDSTwoViewController.o)
ld: symbol(s) not found for architecture x86_64
```

**Comment by kareem-ali-abdelsalam** [comment]
@mu1ex any updates regarding this issue ?

**Comment by mu1ex** [comment]
@kareem-ali-abdelsalam, the new version of the SDK cannot be used on simulator. Its a restriction of the EMV Sdk we use.

**Comment by Diyaa-Gubarah** [comment]
The Apply pay status is failed any idea?

I set all the requirements correctly.

**Comment by mu1ex** [comment]
Have you setup the certificates in NGenius portal

**Comment by Diyaa-Gubarah** [comment]
I did that could you please explain more about how I must do that, and if there's any setup required in xcode it self.

**Comment by mu1ex** [comment]
You will have to add the Apple Pay MID to your entitlements file

**Comment by Diyaa-Gubarah** [comment]
where I can find this `entitlements file` I already added Apple Pay using xcode and it's shows me all the MID and I select the one I want.

Could you please explain more.

Thanks.

**Comment by Diyaa-Gubarah** [comment]
do you mean like this:

`<key>com.apple.developer.proximity-reader.payment.acceptance</key>
<true/>`
