### ISSUE TITLE
Apple pay status failed

### ISSUE THREAD

**Issue by Diyaa-Gubarah** [network-international/react-native-ngenius#25]
I configure the apple pay using this:
1. download the csr from ngenius portal
2. create MID and upload the csr in 1.
3. download certificate from apple portal and uploaded to ngenius.
4. enable apple pay in apple portal
5. then try to create payment .

get {status:"failed"}

**Comment by mu1ex** [comment]
You also need to add the mid in the entitlements file and use it to create the Apple Pay request

**Comment by wang-yazhou** [comment]
I have the same problem. Moreover, I re-uploaded the payment certificate and added the mid in the configuration, but it still reported an error：

const applePayConfig = {
     merchantIdentifier: '*****',
     countryCode: 'AE',
     totalAmount: total,
     currencyCode: 'AED',
     merchantName: '*****',
   };
   try {
     const resp = await initiateApplePay(o, applePayConfig);
   } catch (err) {
     console.log({ err });
   } 

result "err": {"error": undefined, "status": "Failed"}
