### ISSUE TITLE
Android running app have ni sdk issue

### ISSUE THREAD

**Issue by sanjaymj12345** [network-international/react-native-ngenius#26]
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.nimbusds.jose.JWEObject found in modules jetified-ni-three-ds-two-android-sdk-1.0-runtime (com.github.mu1ex:ni-three-ds-two-android-sdk:1.0) and jetified-nimbus-jose-jwt-5.1 (com.nimbusds:nimbus-jose-jwt:5.1)
     Duplicate class com.nimbusds.jose.JWEObject$State found in modules jetified-ni-three-ds-two-android-sdk-1.0-runtime (com.github.mu1ex:ni-three-ds-two-android-sdk:1.0) and jetified-nimbus-jose-jwt-5.1 (com.nimbusds:nimbus-jose-jwt:5.1)
     Duplicate class com.nimbusds.jose.JWSObject found in modules jetified-ni-three-ds-two-android-sdk-1.0-runtime (com.github.mu1ex:ni-three-ds-two-android-sdk:1.0) and jetified-nimbus-jose-jwt-5.1 (com.nimbusds:nimbus-jose-jwt:5.1)
     Duplicate class com.nimbusds.jose.JWSObject$State found in modules jetified-ni-three-ds-two-android-sdk-1.0-runtime (com.github.mu1ex:ni-three-ds-two-android-sdk:1.0) and jetified-nimbus-jose-jwt-5.1 (com.nimbusds:nimbus-jose-jwt:5.1)
     Duplicate class com.nimbusds.jose.Payload found in modules jetified-ni-three-ds-two-android-sdk-1.0-runtime (com.github.mu1ex:ni-three-ds-two-android-sdk:1.0) and jetified-nimbus-jose-jwt-5.1 (com.nimbusds:nimbus-jose-jwt:5.1)
     Duplicate class com.nimbusds.jose.Payload$Origin found in modules jetified-ni-three-ds-two-android-sdk-1.0-runtime (com.github.mu1ex:ni-three-ds-two-android-sdk:1.0) and jetified-nimbus-jose-jwt-5.1 (com.nimbusds:nimbus-jose-jwt:5.1)
     Duplicate class com.nimbusds.jose.Requirement found in modules jetified-ni-three-ds-two-android-sdk-1.0-runtime (com.github.mu1ex:ni-three-ds-two-android-sdk:1.0) and jetified-nimbus-jose-jwt-5.1 (com.nimbusds:nimbus-jose-jwt:5.1)
     Duplicate class com.nimbusds.jose.crypto.AESEncrypter found in modules jetified-ni-three-ds-two-android-sdk-1.0-runtime (com.github.mu1ex:ni-three-ds-two-android-sdk:1.0) and jetified-nimbus-jose-jwt-5.1 (com.nimbusds:nimbus-jose-jwt:5.1)

**Comment by sanjaymj12345** [comment]
Any update on this?
i am already using latest NI package

**Comment by mu1ex** [comment]
The latest version fixes this
