### ISSUE TITLE
Error installing NI-Three-DS-Two-iOS-SDK

### ISSUE THREAD

**Issue by Hasham24** [network-international/react-native-ngenius#27]
After the version upgrade, I face this issue while installing the pod. 

<img width="1164" alt="Screenshot 2022-10-27 at 5 42 55 PM" src="https://user-images.githubusercontent.com/31188910/198287429-b0f126f4-0a31-4005-bf89-8c5f64703628.png">

**Comment by mu1ex** [comment]
The latest version fixes this issue
