### ISSUE TITLE
Error: Program type already present: com.reactlibrary.BuildConfig

### ISSUE THREAD

**Issue by mak12** [network-international/react-native-ngenius#3]
I'm getting this error when I try to build on Android Studio.

This is because of two or more libraries using same package name and it happens generally because of using generic `PackageName`, which in this case is `com.reactlibrary`.

    <manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="com.reactlibrary">       //this should be something unique
    </manifest>

Would it be possible to rename this to something less generic?

**Version**

    network-international/react-native-ngenius: "1.0.8"

**Comment by mu1ex** [comment]
Hi @mak12 thanks for that report. We will fix this and should be available in the next release.

**Comment by mak12** [comment]
Hi @mu1ex that's great, can you please tell expected date of this fix, so we can schedule our release around that.

**Comment by mu1ex** [comment]
Hi @mak12, this issue is fixed in the latest release. Will close this issue for now.
