### ISSUE TITLE
Invalid redeclaration of synthesized implementation for protocol requirement 'rawValue' 

### ISSUE THREAD

**Issue by ramisalem** [network-international/react-native-ngenius#7]
Hello, I am getting this error when building the app " Invalid redeclaration of synthesized implementation for protocol requirement 'rawValue' " 

![Screenshot 2021-08-15 at 6 02 38 PM](https://user-images.githubusercontent.com/25037017/129478728-92a680ae-a018-4a69-92ee-200fbb3a071a.png)
![Screenshot 2021-08-15 at 6 03 06 PM](https://user-images.githubusercontent.com/25037017/129478739-794cb155-52d7-4252-930d-3982ef409d37.png)

Thanks

**Comment by mu1ex** [comment]
This issue should be fixed in version 1.1.1 of the sdk
